### ISSUE TITLE
Static code analyzer cribbing about function return discrepancies 

### ISSUE THREAD

**Issue by lalitpagaria** [outscraper/google-maps-scraper-pyhton#4]
I am integrating Outscrapper's Maps review API with [Obsei](https://github.com/obsei/obsei).
When I integrated SDK with Obsei, mypy started showing error about function return type. For example following function signature shows that they return `dict` - 
```
def google_play_reviews(self, query: list, reviewsLimit: int = 100, sort: str = 'most_relevant', cutoff: int = None,
        rating: int = None, language: str = 'en'
    ) -> dict:


def google_maps_reviews(self, query: list, reviewsLimit: int = 100, limit: int = 1, sort: str = 'most_relevant',
        skip: int = 0, start: int = None, cutoff: int = None, cutoff_rating: int = None, ignore_empty: bool = False,
        coordinates: str = None, language: str = 'en', region: str = None
    ) -> dict:
```
But as per API docs and code they supposed to returning `list` -
```
        if 199 < response.status_code < 300:
            return self._wait_request_archive(response.json()['id']).get('data', [])
```
https://app.outscraper.com/api-docs#tag/Google-Maps/paths/~1maps~1reviews-v2/get

This mismatch causing static code checker to throw the error.

**Comment by vlad-outscraper** [comment]
Hello Lalit,

Thank you for the reporting on this. The fix is pushed into master and will be updated in the next SDK release.
https://github.com/outscraper/google-maps-scraper-pyhton/pull/5

**Comment by lalitpagaria** [comment]
Thanks @vlad-outscraper for faster response.
Closing this issue.
